-- MySQL Script generated by MySQL Workbench
-- Fri Jan 26 21:43:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trainingdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trainingdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trainingdb` DEFAULT CHARACTER SET utf8 ;
USE `trainingdb` ;

-- -----------------------------------------------------
-- Table `trainingdb`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trainingdb`.`department` (
  `id_department` INT NOT NULL,
  `name_department` VARCHAR(45) NULL,
  PRIMARY KEY (`id_department`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainingdb`.`municipality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trainingdb`.`municipality` (
  `id_municipality` INT NOT NULL,
  `name_municipality` VARCHAR(200) NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id_municipality`, `department_id`),
  INDEX `fk_municipality_department_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_municipality_department`
    FOREIGN KEY (`department_id`)
    REFERENCES `trainingdb`.`department` (`id_department`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainingdb`.`gerden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trainingdb`.`gerden` (
  `idgerden` INT NOT NULL AUTO_INCREMENT,
  `gerden_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idgerden`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainingdb`.`type_contagion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trainingdb`.`type_contagion` (
  `idtype_contagion` INT NOT NULL AUTO_INCREMENT,
  `contagion_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idtype_contagion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainingdb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trainingdb`.`status` (
  `idstatus` INT NOT NULL AUTO_INCREMENT,
  `statusc_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainingdb`.`cases_fact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trainingdb`.`cases_fact` (
  `id_case` INT NOT NULL,
  `id_municipality` INT NOT NULL,
  `age` INT NOT NULL,
  `id_type_contagion` INT NOT NULL,
  `id_status` INT NULL,
  `id_gerden` INT NOT NULL,
  `date_symptom` DATETIME NULL,
  `date_death` DATETIME NULL,
  `date_diacnosis` DATETIME NULL,
  `date_recovery` DATETIME NULL,
  PRIMARY KEY (`id_case`),
  INDEX `fk_cases_fact_municipality1_idx` (`id_municipality` ASC) VISIBLE,
  INDEX `fk_cases_fact_type_contagion1_idx` (`id_type_contagion` ASC) VISIBLE,
  INDEX `fk_cases_fact_status1_idx` (`id_status` ASC) VISIBLE,
  INDEX `fk_cases_fact_gerden1_idx` (`id_gerden` ASC) VISIBLE,
  CONSTRAINT `fk_cases_fact_municipality1`
    FOREIGN KEY (`id_municipality`)
    REFERENCES `trainingdb`.`municipality` (`id_municipality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cases_fact_type_contagion1`
    FOREIGN KEY (`id_type_contagion`)
    REFERENCES `trainingdb`.`type_contagion` (`idtype_contagion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cases_fact_status1`
    FOREIGN KEY (`id_status`)
    REFERENCES `trainingdb`.`status` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cases_fact_gerden1`
    FOREIGN KEY (`id_gerden`)
    REFERENCES `trainingdb`.`gerden` (`idgerden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
